export const GAME_ASSETS = {
  reference: "/assets/fleet-key-art-v3.webp",
  driver: "/assets/driver-mascot-v3.webp",
  logo: "/assets/logo-xb-mark-v3.webp",
  brandLockup: "/assets/logo-xb-metal-v3.webp",
  tireToken: "/assets/tire-token.svg",
  billboard: "/assets/billboard.svg",
  asphalt: "/assets/asphalt.svg",
  vehicleProgression: "/assets/vehicle-progression.svg",
  garage: "/assets/garage-hub.svg",
  planetary: "/assets/planetary-hub.svg",
  baseLocal: "/assets/base-local.svg",
  baseRegional: "/assets/base-regional.svg",
  baseGlobal: "/assets/base-global.svg",
  basePlanetary: "/assets/base-planetary.svg",
  buildingEvolution: "/assets/building-evolution.svg",
  tireCompounds: "/assets/tire-compounds.svg",
  routeConditions: "/assets/route-conditions.svg",
  dailyMissions: "/assets/daily-missions.svg",
} as const;
